### ISSUE TITLE
Errors building ubuntu image

### ISSUE THREAD

**Issue by caulagi** [dbond007/Packer#8]
Hi,

I get the following errors when I follow the instructions for building ubuntu image.

```
$ packer build -var-file="variables.pkrvars.hcl" .
Warning: Undefined variable

A "WinRMPassword" variable was set but was not found in known variables. To
declare variable "WinRMPassword", place this block in one of your .pkr files,
such as variables.pkr.hcl

Warning: Undefined variable

A "WinRMUser" variable was set but was not found in known variables. To declare
variable "WinRMUser", place this block in one of your .pkr files, such as
variables.pkr.hcl


Error: Unset variable "SSHPassword"

A used variable must be set or have a default value; see
https://packer.io/docs/configuration/from-1.5/syntax for details.

Error: Unset variable "SSHUser"

A used variable must be set or have a default value; see
https://packer.io/docs/configuration/from-1.5/syntax for details.
```

**Comment by dbond007** [comment]
Hi, yes, thats because the example file was a copy of the one used for windows, the WinRMUser should be SSHUser and the WinRMPassword Should be SSHPassword.

**Comment by dbond007** [comment]
I have updated the example, the username and password error should be gone.

I can not be 100% sure if the ubuntu build works (especially the 20.04) at the moment, as i do not have an esxi 6.7 environment. I was going to test and fix anything after i completed the centos template builds, but I will probably move over to testing / developing the ubuntu one soon since centos is going away.

**Comment by dbond007** [comment]
If you find any other problems please create more cases, I would like to get these builders working well.
